### ISSUE TITLE
CI: Github action concurrency label to cancel stale workflows.

### ISSUE THREAD

**Issue by Archdoog** [stadiamaps/ferrostar#150]
We want to add concurrency labels on all CI tasks so that Github can cancel stale tasks when a new push comes in. To do this, we need to add:

```yml
concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-build
      cancel-in-progress: true
```

To each task at the same level as `runs-on`. Important: we must make sure the group is per task per ref. Meaning it construct a group string like `android-mybranchesref-build`, `android-mybranchesref-test`, etc. That way the task only cancels its match for that branch/PR.

Some tasks like releases should not get this.
